version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver-data:/var/opt/mssql

  blog:
    container_name: server
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "5172:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

volumes:
  sqlserver-data: